### ISSUE TITLE
Finances API and UTF-8

### ISSUE THREAD

**Issue by jerch** [python-amazon-mws/python-amazon-mws#209] opened 2020-09-02 13:24 UTC
`list_financial_events` returns string content as LATIN-1 encoded in `response.parsed`. Since the API is a proper XML API and there is no other encoding is stated anywhere, imho this should always be decoded as UTF-8.

**Comment by GriceTurrble** [comment] 2020-09-02 13:45
Amazon responses are returned in ISO-8859-1 encoding, as described in documentation: https://docs.developer.amazonservices.com/en_US/dev_guide/DG_ISO8859.html. This format is also described as Latin-1.

We mostly take their word for it, so we have been decoding explicitly with ISO-8859-1 to produce Python Unicode string content. Those Unicode strings are then used to produced parsed content, with no other decoding/encoding required.

As seen in #188 and its corrective PR #198, we have had issues decoding implicitly in UTF-8 before. Specifying Latin-1/ISO-8859-1 corrects for this.

---

That aside, are you seeing a specific issue being caused by this decoding logic?

**Comment by jerch** [comment] 2020-09-02 13:49
Thx for th response. Yes, basically all string content shows the unicode characters as "byte decoded". If I place UTF-8 decoding on it in the MWS class, the issue goes away. I know that amazon kinda has encoding issues on their end (we sometimes see mixed up things in CSV reports), it seems the Finance is throughout done with UTF-8 from our experience.

**Comment by GriceTurrble** [comment] 2020-09-02 13:56
Interesting. It would not surprise me to see the different API sections lacking some parity in that regard, despite their docs (i.e. in the Feeds API, there is a `FeedOptions` parameter not documented in official docs, but *is* documented in separate documentation related to VAT invoices; bit of a headache, that one).

On the good news front, #207 is bringing some changes that might make this easier to manage, including overwriting the response encoding and re-parsing content without needing to make changes to PAM code.

I'd love to see some example response content to run tests against, if you'd like to share (being sure to redact proprietary and secret info, of course).

**Comment by jerch** [comment] 2020-09-02 14:32
So here is one example answer (somewhat shortened):
```
<ListFinancialEventsResponse xmlns="http://mws.amazonservices.com/Finances/2015-05-01">
  <ListFinancialEventsResult>
    <FinancialEvents>
      <ProductAdsPaymentEventList/>
      <RentalTransactionEventList/>
      <ServiceFeeEventList>
        <ServiceFeeEvent>
          <FeeDescription>XXXXX... Nähte</FeeDescription>
          <AmazonOrderId>XXXX</AmazonOrderId>
          <SellerSKU>XXXX</SellerSKU>
        </ServiceFeeEvent>
        <ServiceFeeEvent>
          <FeeDescription>XXXXX... Nähte</FeeDescription>
          <AmazonOrderId>XXXX</AmazonOrderId>
          <SellerSKU>XXXX</SellerSKU>
          <FeeList>
            <FeeComponent>
              <FeeAmount>
                <CurrencyAmount>XXXX</CurrencyAmount>
                <CurrencyCode>EUR</CurrencyCode>
              </FeeAmount>
              <FeeType>FBACustomerReturnPerUnitFee</FeeType>
            </FeeComponent>
          </FeeList>
        </ServiceFeeEvent>
      </ServiceFeeEventList>
      <ShipmentSettleEventList/>
      <ServiceProviderCreditEventList/>
      <ImagingServicesFeeEventList/>
      <SellerDealPaymentEventList/>
      <SellerReviewEnrollmentPaymentEventList/>
      <DebtRecoveryEventList/>
      <ShipmentEventList>
        <ShipmentEvent>
          <ShipmentItemList>
            <ShipmentItem>
...
          </ShipmentItemList>
          <AmazonOrderId>XXXX</AmazonOrderId>
          <PostedDate>XXXXX</PostedDate>
          <MarketplaceName>Amazon.de</MarketplaceName>
          <SellerOrderId>XXXX</SellerOrderId>
        </ShipmentEvent>
      </ShipmentEventList>
      <GuaranteeClaimEventList/>
      <TDSReimbursementEventList/>
      <ChargebackEventList/>
      <NetworkComminglingTransactionEventList/>
      <LoanServicingEventList/>
      <RefundEventList>
...
      </RefundEventList>
      <RemovalShipmentEventList/>
      <PerformanceBondRefundEventList/>
      <AffordabilityExpenseReversalEventList/>
      <PayWithAmazonEventList/>
      <AdhocDisbursementEventList/>
      <CouponPaymentEventList/>
      <RetrochargeEventList/>
      <TrialShipmentEventList/>
      <SAFETReimbursementEventList/>
      <RemovalShipmentAdjustmentEventList/>
      <FBALiquidationEventList/>
      <AffordabilityExpenseEventList/>
      <AdjustmentEventList/>
    </FinancialEvents>
  </ListFinancialEventsResult>
  <ResponseMetadata>
    <RequestId>XXXXX</RequestId>
  </ResponseMetadata>
</ListFinancialEventsResponse>
```
Here the problem is the `ä` in the fee descriptions. When I look at the binary response at the same postition, it contains `\xc3\xa4`, which is `ä` in UTF-8. I see the same behavior wherever freetext string might be populated (skus, descriptions) - any non ASCII char there shows up wrong with byte values.
Btw to get the correct `ä` in the XML output above on the terminal, I had to place `data.decode()` in `make_request`.

**Comment by GriceTurrble** [comment] 2020-09-02 15:23
See my edit in previous comment, I've made slight adjustments to #207 in-flight before the merge that should make that process a bit simpler.

These options won't be readily available until that merge is complete, so consider it a preview. :)

**Comment by jerch** [comment] 2020-09-02 16:07
Thx. I tried your patch, I think because of these reasons:
- the encoding setting is not passed on to `xmltodict.parse`, it get lost in `parse_response` (not passed on to `mws_xml_to_dict`)
- `parse_response` uses the `text` attribute of the response, which is already decoded (wrongly)

It works when I correct the issues above and give `response.content` instead to `xmltodict.parse` (and fixing the namespace regexp to support bytes as well).

**Comment by GriceTurrble** [comment] 2020-09-02 17:30
Noted, there was that missing piece. My assumption had been that `.text` would simply be parsed as Unicode, but did not realize that `xmltodict` will actually *re-encode* that to bytes before parsing it, using the encoding given or `'utf-8'` as a default.

One point to mention here:

> `parse_response` uses the `text` attribute of the response, which is already decoded (wrongly)

`MWSResponse.text` ultimately returns [`requests.Response.text`](https://github.com/psf/requests/blob/1f7c88880b2fa56947d844202127782a50e871e7/requests/models.py#L838-L849), which is a property method. It decodes `.content` each time it is called, using either the specified `.encoding` or a detected `.apparent_encoding`. Thus, setting `.encoding` and then calling `.text` *should* return correctly-decoded Unicode.

---

Regardless, I've taken your suggestion under advisement, and updated #207 to use `.content` in the parser, pass the encoding along to the utility methods, and conditionally accept str or bytes in `remove_xml_namespaces`.

**Comment by jerch** [comment] 2020-09-03 06:49
@GriceTurrble Thanks for the fix, this works :+1:

**Comment by 854350999** [comment] 2020-09-14 01:58
it seems like Fulfilment API has the same problem.

This is some returned content

```python
 'ShipmentName': 'FBA (9/1/20, ç¾\x8eä¸\xad69ä»¶', 'BoxContentsSource': 'INTERACTIVE',
```

I used the ```latest``` version

**Comment by jerch** [comment] 2020-09-14 10:14
@854350999 What should `ShipmentName` contain here? This is what I get, if it is the same issue:

```python
>>> 'FBA (9/1/20, ç¾\x8eä¸\xad69ä»¶'.encode('latin-1').decode('utf-8')
'FBA (9/1/20, 美中69件'
```

Is this correct? (brackets not balanced)

@GriceTurrble Do have an idea, which fields might be affected by this? My gut feeling tells me, that the ISO-9958-1 encoding you mentioned above means, that Amazon simply returns bytes unchanged as given somewhere else before. Thus if someone created a product/shipment/whatsoever with UTF-8 they would simply return those UTF-8 bytes unchanged. Do have more insight into this? Not even sure how to test that idea, maybe uploading a product with different encodings applied and requesting other API endpoints on those products would reveal that.

If my idea is true, than I think there not much your lib can do about it. It would basically mean, that any encoding during creation of the entity is kept, thus needs individual decoding on those enitity fields for other API endpoints based on the enitity creation encoding, hmm.

**Comment by 854350999** [comment] 2020-09-14 10:22
Yes, the content like this is correct (the original background content is also missing a parenthesis), but does this mean that I need to re-encode and decode each time? Is this step redundant? This makes me wonder Is the ISO-9958-1 of the official development document necessary?

> @854350999 What should `ShipmentName` contain here? This is what I get, if it is the same issue:
> 
> ```python
> >>> 'FBA (9/1/20, ç¾\x8eä¸\xad69ä»¶'.encode('latin-1').decode('utf-8')
> 'FBA (9/1/20, 美中69件'
> ```
> 
> Is this correct? (brackets not balanced)
> 
> @GriceTurrble Do have an idea, which fields might be affected by this? My gut feeling tells me, that the ISO-9958-1 encoding you mentioned above means, that Amazon simply returns bytes unchanged as given somewhere else before. Thus if someone created a product/shipment/whatsoever with UTF-8 they would simply return those UTF-8 bytes unchanged. Do have more insight into this? Not even sure how to test that idea, maybe uploading a product with different encodings applied and requesting other API endpoints on those products would reveal that.
> 
> If my idea is true, than I think there is not much your lib can do about it. It would basically mean, that any encoding during creation of the entity is kept, thus needs individual decoding on those enitity fields for other API endpoints based on the enitity creation encoding, hmm.

Yes, the response like this is correct (the original background content is also missing a parenthesis), but does this mean that I need to ``re-encode and decode``` each time? Is this step ```redundant```? This makes me wonder Is the ISO-9958-1 encoding of the official development document ```necessary```?

**Comment by 854350999** [comment] 2020-09-14 10:23
@jerch Yes, the response like this is correct (the original background content is also missing a parenthesis), but does this mean that I need to ```re-encode and decode``` each time? Is this step redundant? This makes me wonder Is the ISO-9958-1 encoding of the official development document ```necessary```?

**Comment by jerch** [comment] 2020-09-14 10:39
> ... but does this mean that I need to re-encode and decode each time?

Well thats what I am trying to find out (see the question to @GriceTurrble). If my idea holds, then you prolly have to re-encode/decode into the real encoding yourself, as it is safer for the lib to treat everything as LATIN-1 (the lib cannot know your creation encoding).

**Comment by jerch** [comment] 2020-09-14 11:07
@854350999 If the official statement about ISO-9958-1 (LATIN-1) is true, then there are more issues to that, esp. for the C1 area (byte position 0x80 - 0x9F, they are undefined in LATIN-1, but can occur in UTF-8 as part of multibyte characters) for this reason:

Depending on how strict Amazon's upload/download encoder is with enforcing ISO-9958-1 (or any backend component on their end like their database), those undefined byte positions would raise an exception as undefined (or get filtered). But obviously this does not happen (otherwise entities containing UTF-8 sequences would not be possible at all), it seems they simply swallow anything that does not close a text node in their XML format. But thats not an encoding at all, thats like eating all bytes until a stop byte was found. Therefore I think their document about ISO-9958-1 is misleading, they dont do true ISO-9958-1 transcoding, but direct bytestring mapping. Thus any embedded encoding on a certain entity would survive. Again thats all from observation, my conclusions might be all wrong here.

**Comment by Bobspadger** [comment] 2020-09-14 15:35
Do you have the original response from this for us to look at in its entirety please? (Amazon's XML response)

These are really useful for debugging and fixing items like this. Rather than a whack-a-mole approach we can see whats happening completely.

**Comment by GriceTurrble** [comment] 2020-09-14 17:31
@854350999 to the question of re-encoding, using the newer `MWSResponse` object, no. You have access to the original bytes content which does not change, using `resp.content`. You can also set the encoding manually using `resp.encoding = 'utf-8'` and then call `resp.parse_response()` to regenerate the DotDict in `resp.parsed`.

`requests` also provides easy access to encoding detection in the `Response` object. As this is stored in `MWSResponse.original`, you can use `resp.original.apparent_encoding` to run the detector and return what they think the encoding is (based on `chardet` output).

We *could* simply remove the encoding overwrite in the new code and rely on `requests` to do that for us (the `Response.text` property will decode `.content` every time it is called, using either a specified `.encoding` or the `.apparent_encoding` they detect). That might remove some headaches here.

**Comment by jerch** [comment] 2020-09-14 18:15
@GriceTurrble Not sure if this helps, if my hypothesis about their string handling is true, then you can easily end up with mixed encodings in one API response, example:

- create a product with UTF-8 data in the string fields ==> API would report UTF-8 bytes back (unchanged bytes)
- alter that product, but now using some other encoding (like changing the description with CP1252 encoding) ==> API still would report UTF-8 bytes for unaltered string fields, but now CP1252 bytes for the altered ones

The latter definitely cannot be decoded automatically anymore, as either encoding would break on the other one. Here actually returning the byte content would be the safe bet, and let the lib user re-apply those mixed encodings to the string fields themselves (cannot easily be automated, as it is foreign knowledge during response parsing, unless providing a field-encoding mapping like `{'sku': 'utf-8', 'description': 'latin-1'}`) and so on.

The big BUT here is, we dont know for sure, whether they treat string data populated from outside like that. And there is no sandbox to run extensive integrity tests in. The state of the MWS API is a shame for the biggest marketplace in the world, to say the least :disappointed:.

**Comment by GriceTurrble** [comment] 2020-09-14 18:34
I'm not sure the issue of a separate encoding per field in the same response is even possible. Amazon would have to be manually writing the bytes content with multiple encoding styles in order to achieve that, and then we have an entirely different problem that no one except Amazon could resolve.

Unless there's something strange going on there, we have to rely on a single encoding for the whole response. It's possible that the encoding used could change based on the data Amazon has to produce that response, so that may be cause for just using `.apparent_encoding` detection.

**Comment by jerch** [comment] 2020-09-14 18:50
Yes you are prolly right, it is kinda unlikely they work internally that way (it would make internal comparison in their database almost impossible).

Regarding UTF-8 I found this:
- https://sellercentral.amazon.com/forums/t/-get-amazon-fulfilled-shipments-data--showing-garbled-characters/201562

Not sure how reliable that is, still it indicates, that Amazon uses internally all UTF-8.

Furthermore see this SO thread: https://stackoverflow.com/questions/27694608/how-to-convert-this-utf-8-escaped-string-from-an-amazon-mws-response-to-proper-u

Here Amazon reports `<Address><Name>Ram&#xC3;&#xAD;rez Jones</Name></Address>` in bytes, which can be decoded with:

```python
import html
bytes = b'<Address><Name>Ram&#xC3;&#xAD;rez Jones</Name></Address>'
html.unescape(bytes.decode('latin-1')).encode('latin-1').decode('utf-8')
```
Sadly `html.unescape` does not work with bytes directly, thus needs an additional byte -> latin-1 conversion (which has to be undone afterwards to get to the real UTF-8 string characters).

So it seems, they actually send UTF-8 bytestrings for string fields, furthermore HTML escaped. So the encoding cascade would look like that:

- XML response is in ISO-9958-1
- problematic bytes are escaped as html entities
- string data is a UTF-8 bytestring (thus needs one additional UTF-8 decoding step)

**Comment by elcolumbio** [comment] 2020-09-14 19:38
@GriceTurrble I support your last statement, based from my findings some time ago. Because .apparent_encoding is trying to resolve encoding conflicts (see chardet library and my issue with one latin1 character should be ignored). In general i would prefer a more simple solution like this. It's nice if we are explicit, to the user of this library, about possible encoding issues on multiple levels. I am looking forward to work with some real data again.

**Comment by GriceTurrble** [comment] 2020-09-14 20:15
@jerch I've not seen folks detailing that double-encoding issue before, so unless there's a recent sample of that escaped UTF-8 encoded to Latin-1, I don't think it wise to take action on it. Still, strange stuff.

**Comment by jerch** [comment] 2020-09-14 20:27
@GriceTurrble Yeah I hear you. Will see if I can find more evidence/clues tomorrow. Maybe the best clue would give a look into their API libs (not sure if they are open).

**Comment by GriceTurrble** [comment] 2020-09-14 20:48
A quick perusal of the C# library shows all UTF-8 all day long, a little but of encoding detecting, and zero mention of ISO-8859-1 or Latin-1.

Though if their docs are just out of date to indicate ISO-8859-1, can't say I'm surprised.

Very well, I'll adjust the incoming feature set to work on encoding detection instead of hard coding 8859-1. That should handle most cases, and then we'll just provide docs to handle corner cases in app code as gracefully as possible.

**Comment by Mitalee** [comment] 2020-09-15 02:17
@GriceTurrble : I just had this issue 2 weeks ago with real live data. One of the SKUs had a special character ®. The XML parsing had failed when I tried to get `report.parsed`.

```
>>> a = b'La cr\xaeoisi\xc3\xa8re'
>>> a.decode('utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 5: invalid start byte
>>> a.decode('latin_1')
'La cr®oisiÃ¨re'
```

Off topic, but just now I also came to know about an XML parsing error. One of the SKUs was named `&xyz`. When submitting the feed via `feeds_api.submit_feed`, the utf-8 encoding allowed it to pass, resulting in a MWS error below:

`<ResultDescription>XML Parsing Fatal Error at Line 1, Column 342: The reference to entity &quot;xyz&quot; must end with the &apos;;&apos; delimiter. The reference to entity &quot;xyz&quot; must end with the &apos;;&apos; delimiter.</ResultDescription>`

As a temporary measure, I've fixed it using this - https://wiki.python.org/moin/EscapingXml.

**Comment by jerch** [comment] 2020-09-15 07:34
Offtopic: Is amazon working on a JSON MWS API? Found this here https://github.com/amzn/selling-partner-api-docs, first contribution in August 2020. If you look into the API model specs (https://github.com/amzn/selling-partner-api-models/tree/main/models), they are all defined as

```
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
```
and roughly resemble the XML MWS API endpoints.

**Comment by GriceTurrble** [comment] 2020-09-15 13:37
@jerch Good find. I looked around and found an announcement on that front.

See #212 (Discussion).

**Comment by GriceTurrble** [comment] 2020-10-06 18:08
Adjustments made in August sprint *should* cover these concerns, so closing this. If we have additional concerns with the updated code, please open a new issue with specifics.

I will come back in here to grab samples for later testing, though, so no worries there. :)

**Closed by GriceTurrble** 2020-10-06 18:08 UTC
